databases:
  - name: django-accounts-db
    plan: free
    databaseName: django_accounts
    user: django_accounts

services:
  - type: web
    name: django-accounts
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && cloudflared tunnel --no-autoupdate run --token $CLOUDFLARE_TUNNEL_TOKEN & gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-accounts-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: CLOUDFLARE_TUNNEL_TOKEN
        sync: false
